/// Flutter icons AppIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcon {

  static const _kFontFam = 'AppIcon';
  static const String _kFontPkg = null;

  static const IconData icon_tinnhan = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_facebook = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_down = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_up = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_del = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_share = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_close = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_setting = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_star = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_bag_2 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_bag_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tim = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_flower = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search2 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_google = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pen = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_coupon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_left = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_right = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_upload = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_minus = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_3cham = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);


  //Singleton factory
  static final AppIcon _instance = AppIcon._internal();

  factory AppIcon() {
    return _instance;
  }

  AppIcon._internal();
}
